spring:
  application:
    name: coffee-shop

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  devtools:
    restart:
      enabled: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

aws:
  access-key: ${AWS_ACCESS_KEY_ID_COFFEE}
  secret-key: ${AWS_SECRET_ACCESS_KEY_COFFEE}
  region: ${AWS_REGION_COFFEE}
  bucket-name: ${AWS_BUCKET_NAME_COFFEE}

cutluy:
  api:
    key: ${CUTLUY_API_KEY}
  base-url: https://cutluy.com/v1

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}

#jwt:
#  secret: ${JWT_SECRET}
#  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}