spring:
  application:
    name: coffee-shop
  
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/coffee_shop
  #    username: admin
  #    password: admin@123
  #    driver-class-name: org.postgresql.Driver
  datasource:
    #    url: jdbc:oracle:thin:@localhost:1521/orcl
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: coffee_shop_app
    password: "coffeePka123"
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  #  jpa:
  #    hibernate:
  #      ddl-auto: validate
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  #        dialect: org.hibernate.dialect.PostgreSQLDialect

  #  liquibase:
  #    enabled: true
  #    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  devtools:
    restart:
      enabled: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs


aws:
  access-key: ${AWS_ACCESS_KEY_ID_COFFEE}
  secret-key: ${AWS_SECRET_ACCESS_KEY_COFFEE}
  region: ${AWS_REGION_COFFEE}
  bucket-name: ${AWS_BUCKET_NAME_COFFEE}

khqr:
  profile-id: ${KHQR_PROFILE_ID}
  secret-key: ${KHQR_SECRET_KEY}
  bakong-receiver-id: ${KHQR_BAKONG_RECEIVER_ID}