package com.coffee_shop.coffee_shop.util.enums;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    OTP_SEND,
    OTP_FAILED,
    OTP_VERIFIED,
    TOKEN_REFRESHED,
    REFRESH_TOKEN_REJECTED,
    PERMISSION_DENIED,
    PASSWORD_CHANGED,
    ACCOUNT_STATUS_CHANGED,
    ACCOUNT_CREATED,
    ROLE_PERMISSION_CHANGED,
    STAFF_CREATED,
    STAFF_UPDATED,
    ACCESS_DENIED_DEVICE_MISMATCH
}
